version: '3.8'
services:
services:
  enms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enms
#    image: saneisaya/docker-enms:latest
    restart: always
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - SCHEDULER_ADDR=http://enms-scheduler:8000
#      - VAULT_ADDRESS=${VAULT_ADDRESS}
#      - VAULT_TOKEN=${VAULT_TOKEN}
#      - UNSEAL_VAULT_KEY1=${UNSEAL_VAULT_KEY1}
#      - UNSEAL_VAULT_KEY2=${UNSEAL_VAULT_KEY2}
    volumes:
      - /data/docker/projects:/root/projects
      - /opt/docker/docker-enms/eNMS:/eNMS
    networks:
      - nginx_proxy
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=enms
      - MYSQL_USER=enms
      - MYSQL_PASSWORD=enms_password
    volumes:
      - /data/docker/db_data:/var/lib/mysql
      
    vault-server:
    image: hashicorp/vault:latest
    container_name: vault-server
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - /opt/docker/vault/logs:/vault/logs
      - /opt/docker/vault/file:/vault/file
      - /opt/docker/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      - nginx_proxy
      
  enms-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enms-scheduler
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENMS_ADDR=http://enms:5000
      - ENMS_PASSWORD=admin
      - ENMS_USER=admin
      - VERIFY_CERTIFICATE=0
      - REDIS_ADDR=enms
      - SCHEDULER_ADDR=http://enms-scheduler:8000
      - GUNICORN_ACCESS_LOG=/home/centos/enms/logs/access_scheduler.log
      - GUNICORN_LOG_LEVEL=info
      - DATABASE_URL=mysql://root:PASSWORD@localhost/enms?charset=utf8
    volumes:
      - /data/docker/projects/enms/enms-scheduler:/root/projects
      - /opt/docker/docker-enms/eNMS-Scheduler/eNMS:/eNMS
      - /opt/docker/docker-enms/eNMS-Scheduler/eNMS/scheduler:/scheduler
      - ./logs:/home/centos/enms/logs
    networks:
      - nginx_proxy
    depends_on:
      - mysqld
    # eNMS-Scheduler mysqld
  mysqld:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_DATABASE=enms
    volumes:
      - /data/docker/mysql_data_schedulers:/var/lib/mysql
networks:
  nginx_proxy:
    external: true
